# Generated by Django 6.0.5 on 2026-05-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='university',
            field=models.CharField(blank=True, choices=[('farmgate', 'University of Asia Pacific'), ('dhaka', 'University of Dhaka'), ('buet', 'BUET'), ('nsu', 'North South University'), ('bracu', 'BRAC University'), ('cuet', 'CUET'), ('ruet', 'RUET'), ('other', 'Other')], max_length=100),
        ),
    ]
